version: "3.1"

networks:
  nodedev:

services:
  nodejs:
    build: ./env/nodejs
    container_name: nodejs
    networks: 
      - nodedev
    env_file: env/.env
    environment:
      - PORT=80
      - NODE_ENV=production
    restart: always
    volumes:
      - ~/projects:/home/www/projects
      - ./src:/var/www/src:delegated
      - ./env:/var/env:delegated

  postgres:
    build: ./env/postgres
    container_name: postgres
    networks: 
      - nodedev
    env_file: env/.env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./data/postgres:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

  nginx:
    build: ./env/nginx
    container_name: nginx
    networks: 
      - nodedev
    env_file: env/.env
    volumes:
      - ~/projects:/home/www/projects
      - ./data/nginx/logs:/var/log/nginx
      - ./env/nginx/frontend/upstream/all.conf:/etc/nginx/conf.d/00_upstream.conf
      - ./env/nginx/frontend/sites-available:/etc/nginx/sites-available
      - ./env/nginx/frontend/sites-enabled:/etc/nginx/sites-enabled
    depends_on:
      - nodejs
    ports:
      - 80:80