version: “3.1”

services:
  nodejs:
    build: ./env/nodejs
    container_name: nodejs
    env_file: config/.env
    environment:
      - NODE_ENV=production
    ports:
      - 8088:8088

  db:
    build: ./env/postgres
    container_name: postgres
    env_file: config/.env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./data/postgres:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

volumes:
  postgres:
    driver: local